# use node 18 as the base image with alpine linux OS
FROM node:22-alpine

WORKDIR /use/src/app

COPY package*.json ./

RUN npm ci --only=production

COPY . .

EXPOSE 3002

CMD [ "node", "src/server.js" ]